// SPDX-License-Identifier: MIT
//! Compile-time generator for the ref-jsx table. Walks
//! `design/art/refs/ref-*.jsx` at build time and emits an array of
//! `(filename, include_str!(...))` pairs. The binary therefore has zero
//! runtime fs reads on the input side — all data is baked at build,
//! which both satisfies the static-analysis path-traversal class of
//! findings and gives us a self-contained binary that can't fail at
//! runtime due to a missing or moved input file.
//!
//! Re-runs whenever a file in `design/art/refs/` changes (cargo's
//! `rerun-if-changed` directive).

use std::fs;
use std::path::PathBuf;

fn main() {
    // CARGO_MANIFEST_DIR points at this crate; `../../design/art/refs`
    // climbs to the workspace root.
    let manifest_dir = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo"),
    );
    let refs_dir = manifest_dir
        .join("..")
        .join("..")
        .join("design")
        .join("art")
        .join("refs");
    println!("cargo:rerun-if-changed={}", refs_dir.display());

    let mut entries: Vec<String> = fs::read_dir(&refs_dir)
        .expect("design/art/refs is missing — rendering needs source jsx files")
        .filter_map(|e| e.ok())
        .filter_map(|e| e.file_name().to_str().map(str::to_owned))
        .filter(|name| name.starts_with("ref-") && name.ends_with(".jsx"))
        .collect();
    entries.sort();

    let mut out = String::from("// generated by build.rs — do not edit\n");
    out.push_str("pub static REF_FILES: &[(&str, &str)] = &[\n");
    for name in &entries {
        // Validate name is plain ascii (no path separators, no funny
        // chars) before baking into a string literal — defense in depth
        // for the build script, even though the directory listing is
        // already trusted.
        if !name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '.' || c == '_')
        {
            panic!("refusing to embed jsx with non-ascii-safe filename: `{name}`");
        }
        // Tell cargo to rerun if this specific file changes.
        let abs = refs_dir.join(name);
        println!("cargo:rerun-if-changed={}", abs.display());
        // include_str! resolves relative to the calling source file
        // (the generated table). Easier to compute the path relative
        // to OUT_DIR — but include_str! actually resolves relative to
        // the file containing the macro call, which is OUT_DIR/ref_table.rs.
        // We instead emit absolute paths (cargo accepts them).
        let abs_str = abs
            .canonicalize()
            .expect("ref jsx must exist")
            .to_string_lossy()
            .replace('\\', "/");
        out.push_str(&format!("    ({name:?}, include_str!({abs_str:?})),\n",));
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    fs::write(out_dir.join("ref_table.rs"), out).expect("writing ref_table.rs");
}
