// REF-05 — Trait Mage's Tower interior tile sample sheet, 64×64 (4×4 of 16×16).
// Royal arcane (#3A1559), Old gold (#D2A53F), Mage glow (#9D6FE0).

const T5 = {
  marblePlain: [
    '****************',
    '*XBXBBXBXBXBBXBX',
    '*BBXBBXBBBBBXBB*',
    '*XBXBBXBXBXBBXB*',
    '*BBBBBXBBBBBXBB*',
    '*XBXBBXBXBXBBXB*',
    '*BBBXBBBBBBXBBB*',
    '*XBXBBXBXBXBBXB*',
    '*BBBBBBBBBXBBBB*',
    '*XBXBBXBXBXBBXB*',
    '*BBXBBBBBBBBXBB*',
    '*XBXBBXBXBXBBXB*',
    '*BBBBBXBBBBBXBB*',
    '*XBXBBXBXBXBBXB*',
    '*BBBBBBBBBXBBBB*',
    '****************',
  ],
  marbleRune: [
    '****************',
    '*XBXBBXBXBXBBXB*',
    '*BBXBBXBBBBBXBB*',
    '*XBXBGGGGGGGBXB*',
    '*BBBGGUUUUUGGBB*',
    '*XBGGUGGGGUGGXB*',
    '*BBGUGGLLGGUGBB*',
    '*XBGUGLLLLGUGXB*',
    '*BBGUGLLLLGUGBB*',
    '*XBGUGGLLGGUGXB*',
    '*BBGGUGGGGUGGBB*',
    '*XBXGGUUUUUGGXB*',
    '*BBBBGGGGGGGBBB*',
    '*XBXBBXBXBXBBXB*',
    '*BBBBBBBBBXBBBB*',
    '****************',
  ],
  magicCircle: [
    '****************',
    '****%%%%%%%%****',
    '**%%%********%%*',
    '*%%*GG****GG*%%*',
    '%%*G%%G%%G%%G*%%',
    '%*G%%XGGX%%G*%%*',
    '%*%%X*GG*X%%*%%*',
    '%G%X*G%%G*X%G%%*',
    '%G%X*G%%G*X%G%%*',
    '%*%%X*GG*X%%*%%*',
    '%*G%%XGGX%%G*%%*',
    '%%*G%%G%%G%%G*%%',
    '*%%*GG****GG*%%*',
    '**%%%********%%*',
    '****%%%%%%%%****',
    '****************',
  ],
  stairsUp: [
    '****************',
    '****************',
    '****************',
    'BBBBBBBBBBBBBBBB',
    'XGXGXGXGXGXGXGXG',
    '****************',
    '****************',
    'BBBBBBBBBBBBBB**',
    'XGXGXGXGXGXGXG**',
    '****************',
    '************BBBB',
    'BBBBBBBBBBBB****',
    'XGXGXGXGXGXG****',
    '************XGXG',
    '****************',
    '****************',
  ],
  stairsDown: [
    '****************',
    '****************',
    '****GGGGGGGG****',
    '****%%%%%%%%****',
    'BBBB********BBBB',
    'XGXG********XGXG',
    'BBBBBBBBBBBBBBBB',
    'XGXGXGXGXGXGXGXG',
    'BBBBBBBBBBBBBBBB',
    'XGXGXGXGXGXGXGXG',
    'BBBBBBBBBBBBBBBB',
    'XGXGXGXGXGXGXGXG',
    'BBBBBBBBBBBBBBBB',
    'XGXGXGXGXGXGXGXG',
    'BBBBBBBBBBBBBBBB',
    'XGXGXGXGXGXGXGXG',
  ],
  brickWall: [
    'X**X***X***X***X',
    '*XBBXBBBXBBBXBBB',
    '*BBBBBBBBBBBBBBB',
    'X*BB*BBB*BBB*BBB',
    'X**X***X***X***X',
    'BBBXBBBXBBBXBBBX',
    'BBBBBBBBBBBBBBBB',
    'BBBX*BB*BBB*BBB*',
    'X**X***X***X***X',
    '*XBBXBBBXBBBXBBB',
    '*BBBBBBBBBBBBBBB',
    'X*BB*BBB*BBB*BBB',
    'X**X***X***X***X',
    'BBBXBBBXBBBXBBBX',
    'BBBBBBBBBBBBBBBB',
    'BBBX*BB*BBB*BBB*',
  ],
  sconceLit: [
    'X**X***X***X***X',
    '*XBBXBBBXBBBXBBB',
    '*BBBBBBBBBBBBBBB',
    'X*BB*BBB*BBB*BBB',
    'X**X**XXX**X***X',
    'BBBXBXGGGXXBBBBX',
    'BBBBXG#L#GXBBBBB',
    'BBBX*GLLLG*BBB**',
    'X**X*GLLG**X***X',
    '*XBBXNGGNXBBBXBB',
    '*BBBBNZZNBBBBBBB',
    'X*BB*XNNX*BBB*BB',
    'X**X**X*X**X***X',
    'BBBXBBBXBBBXBBBX',
    'BBBBBBBBBBBBBBBB',
    'BBBX*BB*BBB*BBB*',
  ],
  bookshelf: [
    'XBBBBBBBBBBBBBBX',
    'XBNNNNNNNNNNNNBX',
    'XBNZNZNZNZNZNZBX',
    'XB!OWNGNTNDNYNBX',
    'XBNZNZNZNZNZNZBX',
    'XBOWNTNDNGNYNNBX',
    'XBNZNZNZNZNZNZBX',
    'XBGNNTNNDNYNONBX',
    'XBNZNZNZNZNZNZBX',
    'XBWNGNTNYNNNDNBX',
    'XBNZNZNZNZNZNZBX',
    'XBYNNGNNTNNWNNBX',
    'XBNZNZNZNZNZNZBX',
    'XBOTNNGYNNDNNNBX',
    'XBNZNZNZNZNZNZBX',
    'XBBBBBBBBBBBBBBX',
  ],
  doorway: [
    'X**X*XXXXXXXX*X*',
    '*BB*XGGGGGGXX*BB',
    'BBBBXG****GXBBBB',
    'B*BBXG****GXBB*B',
    'X**XG******GX**X',
    '*BBXG********GBB',
    'BBBXG********GBB',
    'B*BXG********GBB',
    'X**XG********GX*',
    'BBBXG********GBB',
    'BBBXG********GBB',
    'BBBXG********GBB',
    'BBBXG********GBB',
    'BBBXG********GBB',
    'BBBXG********GBB',
    'BBBXG********GBB',
  ],
  crystalPedestal: [
    '****************',
    '*******%%*******',
    '******%MM%******',
    '*****%MIIM%*****',
    '****%MIIIIM%****',
    '****%MIIIIM%****',
    '*****%MIIM%*****',
    '******%MM%******',
    '*******GG*******',
    '******GLLG******',
    '*****GLNNLG*****',
    '****GNNNNNNG****',
    '****XGGGGGGX****',
    '****XGNNNNGX****',
    '****XGGGGGGX****',
    '****XBBBBBBX****',
  ],
  spellBook: [
    '****************',
    '****************',
    '****%%%%%%%%****',
    '***%LCCCCCCL%***',
    '**%LCXLLLLXCL%**',
    '**%LCLLLLLLCL%**',
    '**%LCXLLLLXCL%**',
    '**%LCLLLLLLCL%**',
    '**%LCLLLLLLCL%**',
    '**%LCXLLLLXCL%**',
    '**%LCLLLLLLCL%**',
    '**%LCCCCCCCCL%**',
    '****GGGGGGGG****',
    '*****%%%%%%*****',
    '****************',
    '****************',
  ],
  brazier: [
    '*******%%%******',
    '*****%%LLL%%****',
    '****%LL!!LL%****',
    '****%L!##!L%****',
    '*****%L!!L%*****',
    '******%LL%******',
    '*******GG*******',
    '******GNNG******',
    '*****GNZZNG*****',
    '*****GNZZNG*****',
    '*****XNZZNX*****',
    '*****XNZZNX*****',
    '*****XBZZBX*****',
    '*****XBBBBX*****',
    '****XBBBBBBX****',
    '****XXXXXXXX****',
  ],
  carpetEdge: [
    '****************',
    '****************',
    '****************',
    'XXXXXXXXXXXXXXXX',
    'XGOGOGOGOGOGOGOX',
    'XOOOOOOOOOOOOOOX',
    'XOWOWOWOWOWOWOOX',
    'XOOOOOOOOOOOOOOX',
    'XOOWOOWOOWOOWOOX',
    'XOOOOOOOOOOOOOOX',
    'XOWOWOWOWOWOWOOX',
    'XOOOOOOOOOOOOOOX',
    'XGOGOGOGOGOGOGOX',
    'XXXXXXXXXXXXXXXX',
    '****************',
    '****************',
  ],
  windowStarlight: [
    'XBBBBBBBBBBBBBBX',
    'XBN<<<<<<<<<<NBX',
    'XBN<<<#<<<<<<NBX',
    'XBN<<<<<<<<#<NBX',
    'XBN<<<#<<<<<<NBX',
    'XBN<<<<<<#<<<NBX',
    'XBN<<#<<<<<<<NBX',
    'XBN<<<<<<<<<#NBX',
    'XBN<<<<<#<<<<NBX',
    'XBN<<<<<<<<<<NBX',
    'XBN<<#<<<<<<<NBX',
    'XBN<<<<<<<#<<NBX',
    'XBN<<<<<<<<<<NBX',
    'XBNNNNNNNNNNNNBX',
    'XBBBBBBBBBBBBBBX',
    '****************',
  ],
  wizardTable: [
    '****************',
    '****%%**%%**%%**',
    '***%TM%%TM%%TM%*',
    '****%T%%%T%%%T%*',
    '****ZZZZZZZZZZ**',
    '***ZNNNNNNNNNNZ*',
    '***ZNNNNNNNNNNZ*',
    '***ZBBBBBBBBBBZ*',
    '****Z**********Z',
    '****Z**********Z',
    '****Z**********Z',
    '****Z**********Z',
    '****B**********B',
    '****B**********B',
    '****X**********X',
    '****************',
  ],
  crystalBall: [
    '****************',
    '****************',
    '*****%%%%%%*****',
    '****%MIIIIM%****',
    '***%MII##IIM%***',
    '***%MIIIIIIM%***',
    '***%MIIIIIIM%***',
    '****%MIIIIM%****',
    '*****%%%%%%*****',
    '*******GG*******',
    '*****GGNNGG*****',
    '****GNNNNNNG****',
    '****XGGGGGGX****',
    '****XBNNNNBX****',
    '****XBBBBBBX****',
    '****XXXXXXXX****',
  ],
};

const TILE_ORDER_REF05 = [
  T5.marblePlain, T5.marbleRune, T5.magicCircle, T5.stairsUp,
  T5.stairsDown, T5.brickWall, T5.sconceLit, T5.bookshelf,
  T5.doorway, T5.crystalPedestal, T5.spellBook, T5.brazier,
  T5.carpetEdge, T5.windowStarlight, T5.wizardTable, T5.crystalBall,
];

function composeSheet5(tiles, cols = 4) {
  const out = [];
  const rows = Math.ceil(tiles.length / cols);
  for (let ty = 0; ty < rows; ty++) {
    for (let py = 0; py < 16; py++) {
      let line = '';
      for (let tx = 0; tx < cols; tx++) {
        const tile = tiles[ty * cols + tx];
        if (!tile) line += '.'.repeat(16);
        else line += tile[py];
      }
      out.push(line);
    }
  }
  return out;
}

const REF05_GRID = composeSheet5(TILE_ORDER_REF05, 4); // 64×64

window.REF05 = function REF05({ scale = 4 }) {
  return <PixelArt grid={REF05_GRID} scale={scale} title="REF-05 Mage Tower tiles" />;
};
window.REF05_GRID = REF05_GRID;
window.REF05_ROLES = ['*','%','G','L','N','Z','B','X','M','I','#','<','C','T','D','Y','W','O','!'];
