// SPDX-License-Identifier: MIT
//! Render Pledge & Crown ASCII-grid sprite refs to PNG. Pure Rust;
//! palette + every `design/art/refs/ref-*.jsx` are baked into the
//! binary at build time via `build.rs` + `include_str!`. At runtime
//! this binary parses the embedded sources, looks up palette codes,
//! and writes PNG-32 with transparent background to
//! `<repo>/design/art/refs/png/REF<NN>.png`.
//!
//! ## Why this exists
//!
//! The old pipeline went `.jsx` → React+Babel-standalone in a browser →
//! canvas dataURL → JSON snapshot → Python decoder → PNG. Four moving
//! parts, three of them temptations to fall back to side-renderers
//! when one fails (the 2026-05-02 art-lead batch 3 hit exactly that
//! failure mode). This binary collapses the chain to one Rust process
//! with zero network/browser dependency. Per Matt's no-fallbacks rule.
//!
//! ## Invocation
//!
//! ```text
//! cargo run -p render-refs --release
//! ```
//!
//! Run from the workspace root, or set `RENDER_REFS_OUT=<dir>` to
//! redirect PNG output. By default writes to `<workspace>/design/art/refs/png/`.

use std::collections::HashMap;
use std::path::PathBuf;

use anyhow::{Context, Result, anyhow, bail};
use image::{ImageBuffer, Rgba, RgbaImage};
use regex::Regex;
use tracing_subscriber::EnvFilter;

/// Palette source baked at compile time. `include_str!` makes this a
/// `&'static str` literal — no fs read, no path resolution at runtime.
const PALETTE_SRC: &str = include_str!("../../../design/art/palette.js");

// Generated by build.rs — `pub static REF_FILES: &[(&str, &str)] = ...;`
// where each pair is `(jsx_filename, file_contents_baked_at_build_time)`.
include!(concat!(env!("OUT_DIR"), "/ref_table.rs"));

fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| EnvFilter::new("render_refs=info")),
        )
        .init();

    let palette = Palette::parse(PALETTE_SRC).context("parsing baked palette source")?;
    tracing::info!("palette: {} entries", palette.count());

    let out_dir = resolve_out_dir()?;
    std::fs::create_dir_all(&out_dir)?;

    let mut rendered = 0usize;
    let mut skipped = 0usize;
    for (name, src) in REF_FILES.iter() {
        let png_name = png_name_for(name)?;
        match render_grid(src, &palette) {
            Ok(img) => {
                let dst = out_dir.join(&png_name);
                img.save(&dst)
                    .with_context(|| format!("writing {}", dst.display()))?;
                rendered += 1;
                tracing::info!(
                    "rendered {} -> {} ({}x{})",
                    name,
                    png_name,
                    img.width(),
                    img.height()
                );
            }
            Err(e) => {
                // Some refs (artboard-frame, palette-legend, scaffolding)
                // are not pixel-grid components — they're React layout
                // helpers without a `const REF<NN>_GRID = [...]` literal.
                // Skip with debug log rather than failing the run.
                skipped += 1;
                tracing::debug!("skipping {}: {:#}", name, e);
            }
        }
    }
    tracing::info!(
        "done — {} refs rendered ({} skipped) to {}",
        rendered,
        skipped,
        out_dir.display()
    );
    Ok(())
}

/// Resolve the PNG output directory. `RENDER_REFS_OUT` env wins; else
/// walk upward looking for the workspace marker (Cargo.toml + tools/render-refs)
/// and use `<workspace>/design/art/refs/png/`.
fn resolve_out_dir() -> Result<PathBuf> {
    if let Ok(p) = std::env::var("RENDER_REFS_OUT") {
        return Ok(PathBuf::from(p));
    }
    let mut dir = std::env::current_dir()?;
    loop {
        if dir.join("Cargo.toml").is_file() && dir.join("tools").join("render-refs").is_dir() {
            return Ok(dir.join("design").join("art").join("refs").join("png"));
        }
        if !dir.pop() {
            bail!(
                "could not locate workspace root from current directory; set RENDER_REFS_OUT to specify"
            );
        }
    }
}

/// Map a `.jsx` filename to its expected PNG filename. The `.jsx` files
/// follow `ref-<NN>-<slug>.jsx`; the PNG output is `REF<NN>.png` to
/// match the existing committed artifacts. Variant suffixes (`-v2`)
/// preserve the historical `REF09v2.png` naming.
fn png_name_for(jsx_name: &str) -> Result<String> {
    let stem = jsx_name
        .strip_prefix("ref-")
        .and_then(|s| s.strip_suffix(".jsx"))
        .ok_or_else(|| anyhow!("not a ref-*.jsx file: {jsx_name}"))?;
    let mut parts = stem.splitn(2, '-');
    let num = parts
        .next()
        .ok_or_else(|| anyhow!("missing NN in {jsx_name}"))?;
    if num.len() != 2 || !num.chars().all(|c| c.is_ascii_digit()) {
        bail!("expected 2-digit NN in {jsx_name}, got {num}");
    }
    let suffix = parts
        .next()
        .and_then(|slug| slug.rsplit_once("-v").map(|(_, v)| format!("v{v}")))
        .unwrap_or_default();
    Ok(format!("REF{num}{suffix}.png"))
}

#[derive(Debug)]
struct Palette {
    by_char: HashMap<char, Option<[u8; 4]>>,
}

impl Palette {
    fn parse(src: &str) -> Result<Self> {
        let mut by_char = HashMap::new();

        // Lines like:
        //   K: { hex: '#1B0810', name: 'Inkblood',       group: 'burgundy' },
        //   '!': { hex: '#E63946', name: 'Alarm scarlet', group: 'alarm' },
        //   '.': null,
        //   ' ': null,
        let entry_re = Regex::new(
            r"(?m)^\s*(?P<key>'[^']'|[A-Za-z>])\s*:\s*(?:null|\{\s*hex:\s*'(?P<hex>#[0-9A-Fa-f]{6})')",
        )?;

        for caps in entry_re.captures_iter(src) {
            let key_raw = &caps["key"];
            let ch = parse_palette_key(key_raw)
                .ok_or_else(|| anyhow!("unparseable palette key: {key_raw}"))?;
            let rgba = caps
                .name("hex")
                .map(|m| parse_hex_rgba(m.as_str()))
                .transpose()?;
            by_char.insert(ch, rgba);
        }

        // The palette source uses `'.': null,` and `' ': null,` for
        // transparency — make sure they landed even if the regex
        // missed an unusual key form.
        by_char.entry('.').or_insert(None);
        by_char.entry(' ').or_insert(None);

        if by_char.len() < 3 {
            bail!(
                "parsed only {} palette entries — looks broken",
                by_char.len()
            );
        }
        Ok(Self { by_char })
    }

    fn lookup(&self, c: char) -> Result<Option<[u8; 4]>> {
        self.by_char
            .get(&c)
            .copied()
            .ok_or_else(|| anyhow!("palette has no entry for char '{c}'"))
    }

    fn count(&self) -> usize {
        self.by_char.len()
    }
}

fn parse_palette_key(raw: &str) -> Option<char> {
    if raw.len() == 1 {
        raw.chars().next()
    } else if raw.len() == 3 && raw.starts_with('\'') && raw.ends_with('\'') {
        raw.chars().nth(1)
    } else {
        None
    }
}

fn parse_hex_rgba(hex: &str) -> Result<[u8; 4]> {
    let hex = hex.trim_start_matches('#');
    if hex.len() != 6 {
        bail!("hex color must be 6 chars, got `{hex}`");
    }
    let r = u8::from_str_radix(&hex[0..2], 16)?;
    let g = u8::from_str_radix(&hex[2..4], 16)?;
    let b = u8::from_str_radix(&hex[4..6], 16)?;
    Ok([r, g, b, 0xFF])
}

/// Parse a `.jsx` source string and render its grid to an RgbaImage.
/// Returns Err for refs that don't carry a `const REF<NN>_GRID = [...]`
/// (scaffolding / layout components). The `palette` lookup turns each
/// row character into a pixel; transparent codes (`.`, ` `) leave the
/// pixel at the buffer's RGBA(0,0,0,0) initial value.
fn render_grid(jsx_src: &str, palette: &Palette) -> Result<RgbaImage> {
    let grid_re = Regex::new(r"(?s)const\s+REF\d+(?:_V\d+)?_GRID\s*=\s*\[(?P<body>.*?)\]\s*;")?;
    let caps = grid_re
        .captures(jsx_src)
        .ok_or_else(|| anyhow!("no GRID literal found"))?;
    let body = &caps["body"];

    let line_re = Regex::new(r"'([^']*)'")?;
    let rows: Vec<&str> = line_re
        .captures_iter(body)
        .map(|c| c.get(1).unwrap().as_str())
        .collect();

    if rows.is_empty() {
        bail!("empty grid");
    }
    let width = rows[0].chars().count() as u32;
    let height = rows.len() as u32;
    if !rows.iter().all(|r| r.chars().count() as u32 == width) {
        bail!("irregular row widths (expected {width})");
    }

    let mut img: RgbaImage = ImageBuffer::from_pixel(width, height, Rgba([0, 0, 0, 0]));
    for (y, row) in rows.iter().enumerate() {
        for (x, ch) in row.chars().enumerate() {
            if let Some(rgba) = palette.lookup(ch)? {
                img.put_pixel(x as u32, y as u32, Rgba(rgba));
            }
        }
    }
    Ok(img)
}

#[cfg(test)]
mod tests {
    use super::*;

    const MINI_PALETTE: &str = r#"
window.PALETTE = {
  X: { hex: '#000000', name: 'black' },
  W: { hex: '#FFFFFF', name: 'white' },
  '.': null,
};
"#;

    const MINI_REF: &str = r#"
const REF99_GRID = [
  '.X.',
  'XWX',
  '.X.',
];
"#;

    #[test]
    fn palette_parses_mixed_quoted_and_bare_keys() {
        let p = Palette::parse(MINI_PALETTE).unwrap();
        assert!(p.lookup('X').unwrap().is_some());
        assert!(p.lookup('W').unwrap().is_some());
        assert!(p.lookup('.').unwrap().is_none());
    }

    #[test]
    fn palette_rejects_unknown_char() {
        let p = Palette::parse(MINI_PALETTE).unwrap();
        assert!(p.lookup('?').is_err());
    }

    #[test]
    fn render_grid_produces_correct_dimensions() {
        let p = Palette::parse(MINI_PALETTE).unwrap();
        let img = render_grid(MINI_REF, &p).unwrap();
        assert_eq!(img.width(), 3);
        assert_eq!(img.height(), 3);
        assert_eq!(img.get_pixel(1, 1).0, [0xFF, 0xFF, 0xFF, 0xFF]);
        assert_eq!(img.get_pixel(0, 0).0, [0, 0, 0, 0]);
    }

    #[test]
    fn png_name_handles_simple_and_versioned() {
        assert_eq!(png_name_for("ref-11-smith.jsx").unwrap(), "REF11.png");
        assert_eq!(
            png_name_for("ref-09-worldmap-v2.jsx").unwrap(),
            "REF09v2.png"
        );
    }

    #[test]
    fn baked_palette_parses() {
        let p = Palette::parse(PALETTE_SRC).unwrap();
        // Should have at least the 32 named colors plus '.' and ' '.
        assert!(p.count() >= 30, "got {} palette entries", p.count());
    }

    #[test]
    fn baked_refs_have_at_least_one_grid() {
        let p = Palette::parse(PALETTE_SRC).unwrap();
        let mut grid_count = 0;
        for (_, src) in REF_FILES.iter() {
            if render_grid(src, &p).is_ok() {
                grid_count += 1;
            }
        }
        // We've shipped at least 15 grid-shaped refs at this point
        // (10 reference batch + 2 art-lead batches × 5). Scaffolding
        // refs (artboard-frame, palette-legend, etc.) are filtered out.
        assert!(grid_count >= 15, "got {grid_count} renderable refs");
    }
}
